### ISSUE TITLE
Table or database missing? Armory_slots

### ISSUE THREAD

**Issue by huesoamz** [aletson/trinity-armory#2]
When I try to click on the character that is the error:

Error Number: 1146

Table 'armory.armory_slots' doesn't exist

SELECT `name_en_gb` as `name` FROM `armory_slots` WHERE `id` = '0'

Filename: C:/xampp/htdocs/armory/application/models/Armory_model.php

Line Number: 58

**Comment by velinath** [comment]
did you import the database here: https://github.com/Exodius/WoW-Armory/tree/master/sql

**Comment by huesoamz** [comment]
Yes, if you saw the file armory_0.6.0.1_r604.sql there is not table armory.armory_slots :(

**Comment by velinath** [comment]
Must have been one of the modifications I did I guess. Those have since been lost, unfortunately.

I did some looking, though, and at least I can tell you that what was in that table was simple localizations for the slot names (Head, Shoulder, Wrist, Waist, etc). Just match those up to the ID's and create the table manually and you should be good to go.

**Comment by huesoamz** [comment]
I will appreciate if you recover that table or atleast give me steps for try to saw your app, I only saw a character 50+ 

![image](https://cloud.githubusercontent.com/assets/3308717/24840993/f63d478e-1d4f-11e7-91cc-bb692bb4ff78.png)

**Comment by velinath** [comment]
Wel'p.

I guess I should expand on this. By "lost", I mean the server I was hosting my development copy of this application on had its hard drive stop working. I sent it to data recovery companies and they couldn't retrieve anything.

I...don't really have a way to get the database structure back short of paging through my code and reconstructing it from whatever references I had there. I'll try and work on it, but I have a lot of other stuff on my plate right now so there's really no timeframe.

**Comment by Persephone** [comment]
@aletson Is there any way you could get those tables back? :P As I can re-create the tables from the php files, but i have no clue about the data.

Thanks in advance!
